export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_PERFORMANCE_DATA_SUCCESS = 'FETCH_PERFORMANCE_DATA_SUCCESS';
