export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_PERFORMANCE_DATA_SUCCESS = 'FETCH_PERFORMANCE_DATA_SUCCESS';
export const FETCH_SHOPS_DATA_SUCCESS = 'FETCH_SHOPS_DATA_SUCCESS';
export const FETCH_LOGIN_DATA_SUCCESS = 'FETCH_LOGIN_DATA_SUCCESS';
export const FETCH_STOCK_DATA_SUCCESS = 'FETCH_STOCK_DATA_SUCCESS';
